---
- hosts: localhost
  vars_files:
  - local.config.yml
  roles:
  - role: roles/macos
    tags: [macos]
    when: ansible_os_family == 'Darwin'
  - role: roles/debian
    tags: [debian]
    when: ansible_os_family == 'Debian'
  - role: roles/ssh
    tags: [ssh]
  - role: roles/dotfiles
    tags: [dotfiles]
  tasks:
  - name: Dump hostvars
    tags: [never, dump]
    debug:
      var: hostvars[inventory_hostname]
  - name: Ensure fly
    tags: [packages]
    get_url:
      url: "{{ fly_url }}"
      dest: "{{ lookup('env', 'HOME') }}/.local/bin/fly"
      mode: "u=rwx,g=rx,o=rx"
  - name: Ensure helm diff
    tags: [packages]
    shell: helm plugin install https://github.com/databus23/helm-diff

