---
- hosts: localhost
  vars_files:
  - local.config.yml
  roles:
  - role: roles/macos
    tags: [macos]
    when: ansible_os_family == 'Darwin'
  - role: roles/debian
    tags: [debian]
    when: ansible_os_family == 'Debian'
  - role: roles/ssh
    tags: [ssh]
  - role: roles/dotfiles
    tags: [dotfiles]
  - role: roles/enpass-cli
    tags: [packages]
  - role: roles/offlineimap
    tags: [offlineimap, services, never]
    when: ansible_os_family == 'Debian'
  - role: roles/rust
    tags: [packages]
  - role: roles/fly
    tags: [packages]
  - role: roles/helm-diff
    tags: [packages]
  - role: roles/multiarch-container-builds
    tags: [packages]
  tasks:
  - name: Dump hostvars
    tags: [never, dump]
    debug:
      var: hostvars[inventory_hostname]
