---
- hosts: localhost
  roles:
  - role: roles/macos
    tags: [macos]
    when: ansible_os_family == 'Darwin'
  - role: roles/debian
    tags: [debian]
    when: ansible_os_family == 'Debian'
  tasks:
  - name: Dump hostvars
    tags: [never, dump]
    debug:
      var: hostvars[inventory_hostname]
  - name: Ensure fly
    tags: [packages]
    get_url:
      url: "{{ fly_url }}"
      dest: "{{ lookup('env', 'HOME') }}/.local/bin/fly"
      mode: "u=rwx,g=rx,o=rx"

  - name: Ensure ssh keypair
    tags: [ssh]
    openssh_keypair:
      path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
      type: ed25519
      regenerate: full_idempotence

  - name: Ensure ssh key on github
    tags: [ssh,git]
    github_key:
      name: "{{ lookup('env', 'USER') }}@{{ hostname }}"
      token: "{{ github_token }}"
      pubkey: "{{ lookup('file', lookup('env', 'HOME') ~ '/.ssh/id_ed25519.pub') }}"

  - name: Ensure ssh key on gitea
    tags: [ssh, git]
    github_key:
      name: "{{ lookup('env', 'USER') }}@{{ hostname }}"
      token: "{{ gitea_token }}"
      pubkey: "{{ lookup('file', lookup('env', 'HOME') ~ '/.ssh/id_ed25519.pub') }}"
      api_url: "{{ gitea_api_url }}"
