= My dev-machine setup
:source-highlighter: rouge
:icons: font

This ansible-playbook will setup my development machines and prepare them for work.

== Prepararation
The setup is a bit different for linux and macos, since I can use the local package-manager on linux.
Though on macos I need to install `brew` first!
In both cases we need to install `ansible` and `git` though.

.Prepararation on Debian and Ubuntu
[source,bash]
----
sudo apt install ansible git
----

.Prepararation on Macos
[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install ansible git
----

=== password.txt
To execute the playbook we need a password for the vault.
This password has to be stored in a `password.txt` containing exactly one line with only the password as content.

[NOTE]
Use a secure password and keep it in a password-manager.

== Setup
Make sure to configure the local environment:
This is done by copying `global_vars/localhost/local.config.yml.tpl` to `global_vars/localhost/local.config.yml` and adjust it to the local conditions.

[source,bash]
----
cp global_vars/localhost/local.config.yml.tpl global_vars/localhost/local.config.yml
vi $_
----

[NOTE]
We do not have installed anything yet, so we can only use the available tools of the environment.

After the configuration the setup is very simple:

[source,bash]
----
git clone git@gitea.nehrke.info:nemoinho/dev-machine.git ~/Development/nemoinho/dev-machine
cd $_
# make sure that we're on the latest requirements
ansible-galaxy install -r requirements.yml --upgrade
ansible-playbook main.yml
----
